"""adiciona a coluna deletado na tabela alunos

Revision ID: 05bdfdf5da7c
Revises: e95738b1d1fd
Create Date: 2026-06-07 15:27:54.137994

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "05bdfdf5da7c"
down_revision: Union[str, Sequence[str], None] = "e95738b1d1fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "alunos",
        sa.Column("deletado", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("alunos", "deletado")
    # ### end Alembic commands ###
