"""model nota migrado para sqlalchemy2

Revision ID: 17f351e1289a
Revises: 5afbff23b9ec
Create Date: 2026-07-15 01:42:59.396815

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "17f351e1289a"
down_revision: Union[str, Sequence[str], None] = "5afbff23b9ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notas", sa.Column("id_aluno", sa.Integer(), nullable=False))
    op.alter_column(
        "notas", "nota", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
    )
    op.drop_constraint(op.f("notas_aluno_fkey"), "notas", type_="foreignkey")
    op.create_foreign_key(None, "notas", "alunos", ["id_aluno"], ["id"])
    op.drop_column("notas", "aluno")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notas", sa.Column("aluno", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "notas", type_="foreignkey")
    op.create_foreign_key(
        op.f("notas_aluno_fkey"), "notas", "alunos", ["aluno"], ["id"]
    )
    op.alter_column(
        "notas", "nota", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
    )
    op.drop_column("notas", "id_aluno")
    # ### end Alembic commands ###
