"""adiciona unique=True no email

Revision ID: 5afbff23b9ec
Revises: 05bdfdf5da7c
Create Date: 2026-07-14 03:19:48.210107

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "5afbff23b9ec"
down_revision: Union[str, Sequence[str], None] = "05bdfdf5da7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "usuarios", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "usuarios", type_="unique")
    # ### end Alembic commands ###
