"""adiciona a coluna ano na tabela notas

Revision ID: c471774a396b
Revises: 2e472caf1dbf
Create Date: 2026-06-04 16:02:44.093329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c471774a396b'
down_revision: Union[str, Sequence[str], None] = '2e472caf1dbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notas', sa.Column('ano', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notas', 'ano')
    # ### end Alembic commands ###
