"""cria a tabela de convites

Revision ID: e95738b1d1fd
Revises: c471774a396b
Create Date: 2026-06-06 14:15:21.893932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e95738b1d1fd'
down_revision: Union[str, Sequence[str], None] = 'c471774a396b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('convites')
    # ### end Alembic commands ###
